apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-flask
  labels:
    app: rostbot
    service: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rostbot
      service: flask
  template:
    metadata:
      labels:
        app: rostbot
        service: flask
    spec:
      imagePullSecrets:
        - 
          name: gitlab-registry
      containers:
        - name: flask
          image: gitlab.liu.se:5000/tddc88-company-1-2020/deploy/flask:latest
          imagePullPolicy: Always
          env:
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
