apiVersion: v1
kind: Service
metadata:
  labels:
    app: directline
  name: directline-backend-service
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: directline
    service: backend
  type: ClusterIP
